# MongoDB Configuration
spring.mongodb.uri=mongodb+srv://USER:PASSWORD@moviesoscardb.0peko8f.mongodb.net/?appName=MoviesOscarDB
# spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=mydb

# Server Configuration
server.port=8080

# Logging para ver las consultas (util para debug)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.com.apioscarsmovies.backend=DEBUG


